"""Pydantic data schemas for RepoMind Grounded LLM Intelligence Layer."""

from typing import Optional, Literal
from pydantic import BaseModel, Field


class EvidenceItem(BaseModel):
    """Verifiable repository code evidence supporting an LLM claim."""
    file: str = Field(..., description="Relative repository file path")
    line_start: int = Field(..., description="Starting line number in source code")
    line_end: int = Field(..., description="Ending line number in source code")
    symbol: str = Field(..., description="Function, class, or entity symbol name")
    type: str = Field("function", description="Evidence type: function, class, route, finding, test, import, data_flow")
    reason: str = Field(..., description="Why this evidence was selected and what it proves")
    snippet: Optional[str] = Field(None, description="Actual verified source code lines from repository")


class StructuredImpact(BaseModel):
    """Deterministic blast-radius and impact context."""
    files: list[str] = Field(default_factory=list, description="Affected file paths")
    functions: list[str] = Field(default_factory=list, description="Affected function names / callers")
    risk_score: Optional[int] = Field(None, description="Authoritative 0-100 score from RepoMind Risk Engine")
    risk_level: Optional[str] = Field(None, description="Authoritative classification: LOW, MODERATE, HIGH, CRITICAL")
    blast_radius_summary: Optional[str] = Field(None, description="Concise explanation of structural reach")


class StructuredLLMResponse(BaseModel):
    """Strictly structured, evidence-grounded response schema for RepoMind."""
    id: str = Field(..., description="Unique response identifier")
    answer: str = Field(..., description="Comprehensive natural-language answer grounded in evidence")
    summary: str = Field(..., description="Executive 1-2 sentence developer summary")
    confidence: Literal["high", "medium", "low"] = Field("high", description="Grounded confidence level")
    mode: str = Field("understand", description="Reasoning mode applied: understand, architecture, impact, security, debug, refactor, explain, general")
    audience: Literal["senior", "junior"] = Field("senior", description="Target audience perspective")
    evidence: list[EvidenceItem] = Field(default_factory=list, description="Verifiable citations from repository")
    related_symbols: list[str] = Field(default_factory=list, description="Symbols connected to inquiry")
    impact: StructuredImpact = Field(default_factory=StructuredImpact, description="Authoritative risk and blast radius")
    recommendations: list[str] = Field(default_factory=list, description="Actionable engineering guidance")
    limitations: list[str] = Field(default_factory=list, description="Explicit boundaries and unavailable data disclosures")
    is_fallback: bool = Field(False, description="True if generated by deterministic intelligence due to LLM unavailability")
    provider: str = Field("deterministic", description="Provider used: gemini, openai, anthropic, or deterministic")
    model: Optional[str] = Field(None, description="Specific model utilized")
    latency_ms: Optional[float] = Field(None, description="Inference latency in milliseconds")


class AskLLMRequest(BaseModel):
    """Request payload for grounded LLM Q&A."""
    repository_id: str = Field(..., description="Analyzed repository session ID")
    question: str = Field(..., description="Developer question about the repository")
    mode: str = Field("understand", description="Mode: understand, architecture, impact, security, debug, refactor, explain, general")
    audience: str = Field("senior", description="Audience: senior or junior")
    target_symbol: Optional[str] = Field(None, description="Optional target function or class name")
    target_file: Optional[str] = Field(None, description="Optional target file path")


class ExplainCodeRequest(BaseModel):
    """Request payload to explain a specific file or symbol."""
    repository_id: str = Field(..., description="Analyzed repository session ID")
    file: str = Field(..., description="File path to explain")
    symbol: Optional[str] = Field(None, description="Optional specific function or class name")
    audience: str = Field("senior", description="senior or junior")


class ImpactExplainRequest(BaseModel):
    """Request payload to explain blast radius and risk consequences of changing a symbol."""
    repository_id: str = Field(..., description="Analyzed repository session ID")
    symbol: str = Field(..., description="Target function or entity name (e.g. process_order)")
    file: Optional[str] = Field(None, description="Target source file")
    audience: str = Field("senior", description="senior or junior")


class RefactorExplainRequest(BaseModel):
    """Request payload to explain proposed refactoring decomposition and verification."""
    repository_id: str = Field(..., description="Analyzed repository session ID")
    target_function: str = Field(..., description="Function being refactored")
    file: Optional[str] = Field(None, description="Target source file")
    audience: str = Field("senior", description="senior or junior")


class LLMStatusResponse(BaseModel):
    """Health and configuration status of the external LLM provider."""
    status: str = Field(..., description="Overall status: available, offline_fallback, misconfigured, timeout")
    provider: str = Field(..., description="Active or configured provider name")
    model: str = Field(..., description="Configured model identifier")
    configured: bool = Field(..., description="True if API key is present in environment")
    available: bool = Field(..., description="True if provider passed live connectivity check")
    message: str = Field(..., description="User-friendly status description")
    metrics: dict[str, int | float] = Field(default_factory=dict, description="Safe request and latency telemetry")
